# Generated by Django 4.0.2 on 2022-02-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('upfront_commission_rate', models.FloatField()),
                ('trial_commission_rate', models.FloatField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'lender',
                'verbose_name_plural': 'lenders',
                'db_table': 'lender',
                'ordering': ['id'],
            },
        ),
    ]
